### ISSUE TITLE
main.cpp build error

### ISSUE THREAD

**Issue by gokulsukumar03** [SaschaWillems/Vulkan-glTF-PBR#18]
![screenshot 2019-01-31 at 2 42 30 pm](https://user-images.githubusercontent.com/10562584/52043977-fcd1a380-2566-11e9-8e11-0365bfb28ced.png)

I have cloned and update the module 
(git submodule init
git submodule update)

But showing error in all cpp files.

**Comment by SaschaWillems** [comment]
Please try to add more details to your issues, otherwise I don't have a chance of knowing what's your problem. 

I can only guess that the screenshot you provided highlights missing functions in red?

If so, and the missing ones are the Vulkan functions, then you need to include the proper Vulkan headers.
