### ISSUE TITLE
Relative paths not working on Windows

### ISSUE THREAD

**Issue by nihalkenkre** [SaschaWillems/Vulkan-glTF-PBR#29]
Using CMake 3.15.2 on Windows 10.

Generating the project inside a build directory 

![vulkangltfpbr1](https://user-images.githubusercontent.com/463752/66115624-d335b400-e5ee-11e9-8d85-d56f50df947b.png)

So I replaced the relative path strings with the hard coded folder path, for shaders, fonts, and assets. instead of the ./../data string and got it working.

thank you for the project

**Comment by BattleAxeVR** [comment]
Had the same problem using Visual Studio from /build folder. I had to replace ./../data with ../../data in four places because the working folder cmake creates in visual studio projects is relative to the vcxproj, which is under build/src. So to get to data you need to drop down two levels of folders, not one. 

In general, relative paths should work both within Visual Studio debugger and if you click on the .bin directly. So the working folder should be the solution folder, which should be assumed to be under the root in /build probably. 

In that case, the actual relative path on windows would be still ./../data. So no code changes necessary. Or, if there are code changes to be made, it should be to search for /data at . or ./.. or ./../.. . Lots of other samples do this relative path searching dynamically. 

I'm not sure what command line change is to make solution dir the default working dir in cmake, but it would be worth adding it to the README..

The one improvement I do think should be made to this repo, is to remove the duplicated / hardcoded "./../data" prefix and make it a define so you only need to change it in one place, and any time you try to read an asset it concatenates the string. Could be done at runtime (or at compile time with some macros).

**Comment by Radagan** [comment]
Same for building on macOS or Linux using CMake where the build directory is a child of the main project directory.
