### ISSUE TITLE
Two-sided triangles or depth issue

### ISSUE THREAD

**Issue by tigrazone** [SaschaWillems/Vulkan-glTF-PBR#52]
Please look at video and how to fix these artifacts?
I want to use objects like "solid" and I want it all visible, not lost on some depth
https://youtu.be/fNzigld0rLY

**Comment by LudwigFriedmann** [comment]
I think your problem is called [frustum culling](https://learnopengl.com/Guest-Articles/2021/Scene/Frustum-Culling) :) The frustum is the volume of the virtual world that you're able to see. Everything else is culled for the sake of better performance and in order to prevent unwanted effects. The frustum originates at the observer's eye or camera and is defined by vertival/horizontal opening angles, a near plane and a far plane. To solve your problem, you may have to adjust the near/far plane distance. Be careful though - this will induce optical effects

**Comment by SaschaWillems** [comment]
Exactly. This is not an issue per see, but expected behaviour. The scene is clipped at the near plane. If you want to avoid that you could scale the model, move the near plane closer to the camera (note that you'll loose depth precision with this) or implemented inverted depth.

**Comment by tigrazone** [comment]
Ok. Where is in code and how to fix it?

**Comment by SaschaWillems** [comment]
Near and far clipping planes are defined in the [camera perspective](([WWP L 8IK-2](https://github.com/SaschaWillems/Vulkan-glTF-PBR/blob/17849c501cc9523ea72e56918c55359512d3406f/src/main.cpp#L1699) ) setup. Before you blindly change the near plane to a very small value, you may want to read up on possible implications and why it may not be the best idea to just use a small near clipping plane value.

**Comment by SaschaWillems** [comment]
Just a quick note: As this is not an issue per-se with the project, it might be better to ask this in the [discussions tab of the project](https://github.com/SaschaWillems/Vulkan-glTF-PBR/discussions).
