### ISSUE TITLE
How to make the backgrund sharp?

### ISSUE THREAD

**Issue by alexkh** [SaschaWillems/Vulkan-glTF-PBR#53]
On all examples the background is blurred. What is the correct way to make it sharp for using in a game?

Also, for some reason my converted hdr image appears in the demo upside-down. What would be the correct way to make it right side up again?

Best regards,

-Alexandre

**Comment by SaschaWillems** [comment]
> On all examples the background is blurred. What is the correct way to make it sharp for using in a game?

That's intentional. I'm binding the pre-filtered cubemap for the background descriptor set. If you instead want to display the unfiltered source background image, just bind the `` texture to the background's descriptor set instead of the `prefilteredCube` texture and sample from lod 0 instead of 1.5 in skybox.frag.

> Also, for some reason my converted hdr image appears in the demo upside-down. What would be the correct way to make it right side up again?

I don't know how you create the cubemap, but easiest way would be flipping it in your conversion process with the tool you use for creating the cubemap. If that's not possible, simply flip uv's in the shaders.
