### ISSUE TITLE
[Question] Using this code as a guide to writing a glTF scene loader

### ISSUE THREAD

**Issue by Radagan** [SaschaWillems/Vulkan-glTF-PBR#58]
While following this code as an example of loading glTF files to write a glTF loader in mine, I have encountered one problem and one question. 

The problem represents hitting an area of Vulkan that is new to me: multiple descriptor sets, specifically where the second is dynamically formed and complex (glTF). I already have a descriptor set 0 used to render other objects. I know I need to have the first point to the new sets generated while loading the glTF scene, but I'm struggling with the details of doing that. Any advice would be greatly appreciated, even just pointing me to a good example showing this sort of multiple descriptor set use. 

Descriptor sets seem a lot like Latin grammar: everything has a place and everything must be in its place... 😀

@SaschaWillems My question is regarding the difference between this repo and the glTF examples (the simpler ones) in your main samples repo. In this more complex example, you use gli and the main example repo uses KTX. It would seem to my inexperienced Vulkan eyes that KTX would be a better choice. What motivated you to use gli over KTX?

**Comment by SaschaWillems** [comment]
The difference is historic. My samples initially also used gli, but since that is no longer maintained I updated them to use KTX. It's something I want to do for this repo too, but haven't found the time to do so.

But just for loading glTF models it doesn't matter unless you use models with the KTX extension. Otherwise images for the models are loaded via stb_image as part of tinyGLTF.

**Comment by Radagan** [comment]
@SaschaWillems Thank you. As I'm still trying to get the Helmet to load in my code, I'll stick with what it in this repo then. One complexity at a time!
